sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_install:
  - openssl aes-256-cbc -K $encrypted_ed0548e35004_key -iv $encrypted_ed0548e35004_iv -in deploy_key.enc -out deploy_key -d
before_script:
  - npm prune
after_success:
  - bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "ed0548e35004"
    - COMMIT_AUTHOR_EMAIL: "vincentriemer@gmail.com"
