sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- stable
before_script:
- npm prune
after_success:
- npm run deploy
env:
  global:
  - GH_REF: github.com/vincentriemer/io-808.git
  - secure: zr6YTrnR2CFGzkhjl+cTQsPnS8Ki86SS+wdx9ykX8Uk7e71tIptNq89WviXLigP3FZFufxeXqUO7gN4ScNyHc1ZvlH5CoXptBO+vl0Xwpa0ET+UUEx/zsW0L9sU3t754LssNYXnAo1YFUOnG51AG5DXtlYDPxq725AjkiAyfOsNscTC212Ice4g5sEsjG/74/qhPwJjBF8rnIl1kHQmGOMU4BtIv2X32csk5dgsObjo7hHLtBmzryvRsizP7+k0xxPytYZQfXggKw5d4HV+3umQkbVP/LLFyEo6ij4YS40y79uiP8m17qEv8bLqwTauDvcvY3LjnAqq1vIuPCeNnt0StXua/4GRHUBl05F2HG8FAlhpQ6quAUMGkVrxCfURqfMyZVP15e49mlq8F3vfJRRX8PV0XN7/863AJ6F7Arkh37Tm9zZy+xtPj2rloTKPjD+hrrXRqYdLz50JbaRCHxT1uvbLb7pmmCAE/39jaIcLqtwyIwUt5221PJJFV5RCemH8DCj2gjXGHC97D0oLFsJ4/02clmc8cHWxt7kc4+UVoJv48f1Jv2HbPCxflvAOYnLF5mgFbxy8IlrcgRMZvT3JDtobA9wYhtLQe4luNuTt4zotf97pndWCLR40NHr49lXeKod3chtA+uYYJ8ZPtsvszhwGxGqCoRVG4RsBHxCQ=
